### ISSUE TITLE
Improve Header of Website

### ISSUE THREAD

**Issue by meinhoonharsh** [gdscrgpv/meme-king#1]
#### Description
The current Header of the Website is Very Unstructured and has no CSS, So we need to make it look good.

#### Screenshots
![image](https://user-images.githubusercontent.com/64343449/136250596-4f062720-1e58-41b4-b151-71ae19bafe3b.png)

#### Files
`/style.css` - Contains the Styling for Website
`/index.html` - Contains HTML code for the Website

#### To Reproduce
just visit [https://gdscrgpv.github.io/meme-king/](https://gdscrgpv.github.io/meme-king/)

#### Tasks
- [ ] Write the Styling in `/style.css`
- [ ] Chage HTML code in `/index.html` (If needed)

**Comment by CharleneHoogkamer** [comment]
Could you assign this to me?

**Comment by meinhoonharsh** [comment]
Its yours now @CharleneHoogkamer

**Comment by Dliz05** [comment]
Could you please assign this to me..?

**Comment by bahubaliramji** [comment]
i want to work on that

**Comment by meinhoonharsh** [comment]
Sorry @Dliz05 @bahubaliramji 
This issue has been already fixed, therefore closing this issue
